version: '3'

services:
  front-ressources-relationnelles:
    image: ghcr.io/antoinebhr/front-ressources-relationnelles/frontend_image:latest
    container_name: front-ressources-relationnelles
    ports:
      - "8100:8100"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=false
      - WATCHTOWER_POLL_INTERVAL=300
      # Identifiants pour le repository du backend
      - REPO_USER_BACKEND=AntoineBhr 
      - REPO_PASS_BACKEND=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
      # Identifiants pour le repository du frontend
      - REPO_USER_FRONTEND=AntoineBhr 
      - REPO_PASS_FRONTEND=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
    command: --interval 300 
