version: '3'

services:
  front-ressources-relationnelles:
    image: ghcr.io/antoinebhr/front-ressources-relationnelles/frontend_image:latest
    container_name: front-ressources-relationnelles
    ports:
      - "8100:8100"
