name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install Ionic CLI
      run: npm install -g @ionic/cli

    - name: Build Ionic app
      run: ionic build --prod

    - name: Install Capacitor
      run: npm install @capacitor/cli

    - name: Sync Capacitor
      run: ionic cap sync android

    - name: Make gradlew executable
      run: chmod +x android/gradlew

    - name: Build Android APK
      run: cd android && ./gradlew assembleRelease --stacktrace --info --debug

    - name: List APK files
      run: ls -alh android/app/build/outputs/apk/release/

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: android/app/build/outputs/apk/release/app-release-unsigned.apk
