name: Build iOS IPA Debug

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install Ionic CLI
      run: npm install -g @ionic/cli

    - name: Build Ionic app
      run: ionic build --prod

    - name: Install Capacitor
      run: npm install @capacitor/cli

    - name: Sync Capacitor
      run: ionic cap sync ios

    - name: Create exportOptions.plist
      run: echo '<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>method</key><string>development</string><key>signingStyle</key><string>manual</string></dict></plist>' > ios/App/exportOptions.plist

    - name: Build IPA Debug
      run: |
        cd ios/App
        xcodebuild -workspace App.xcworkspace -scheme App -sdk iphoneos -configuration Debug archive -archivePath $PWD/build/App.xcarchive
        xcodebuild -exportArchive -archivePath $PWD/build/App.xcarchive -exportOptionsPlist $PWD/exportOptions.plist -exportPath $PWD/build

    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: ios-ipa
        path: ios/App/build/App.ipa
